[project]
name = "agent-with-mcp-support"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.32.1",
    "langchain-groq>=0.3.2",
    "langchain-openai>=0.3.19",
    "mcp-use>=1.3.0",
]
